name: Greetings

on: 
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Greet first-time contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "🎉 Welcome to HanaGrooveBot! Thanks for opening your first issue. I'll review it and get back to you as soon as I can. Feel free to ask any questions!"
          pr-message: "🚀 Thanks for your first pull request to HanaGrooveBot! I’ll review it and get back to you shortly. If you have any questions or need help, just let me know!"
